# -- Site Configuration --
# https://blowfish.page/docs/getting-started/

baseURL = "https://www.plucky.wang/"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0

buildDrafts = false
buildFuture = false

enableEmoji = true
enableGitInfo = true

[pagination]
  pagerSize = 100

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

ignoreLogs = ['warning-goldmark-raw-html']

[markup.tableOfContents]
  startLevel = 1
  endLevel = 3

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^GITHUB_SHA$']

[outputs]
  home = ["HTML", "RSS", "JSON"]
